[accessibility]
ui_scale = 0.95000000670552254

[audio]
enable_overdrive = true

[bar.default]
center = [ "workspaces" ]
end = [
    "media",
    "tray",
    "volume",
    "clipboard",
    "network",
    "bluetooth",
    "brightness",
    "battery",
    "control-center",
    "session"
]
reserve_space = false
smart_auto_hide = true
start = [ "clock" ]

[control_center]
sidebar = "full"
sidebar_section = "full"

[desktop_widgets]
enabled = false
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
icon_size = 33
reserve_space = false
shadow = false
smart_auto_hide = true

[location]
address = ""

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box"]
    box_height = 229.0
    box_width = 810.0
    cx = 720.0
    cy = 701.5
    output = ""
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_weather = true

[nightlight]
enabled = true
force = true

[shell]
app_icon_color = "primary"
corner_radius_scale = 0.90000001341104507
font_family = "MesloLGL Nerd Font"
panel_anchor_bar = "default"
polkit_agent = true
popup_shadows = false

    [shell.launcher]
    fetch_exchange_rates = false

    [shell.panel]
    clipboard_placement = "attached"
    launcher_placement = "attached"
    launcher_position = "bottom_center"
    open_near_click_clipboard = true
    open_near_click_session = true
    open_near_click_wallpaper = true
    polkit_placement = "attached"
    shadow = false

    [shell.screenshot]
    directory = "/home/USERPLACEHOLDER/Pictures/Screenshots"

    [[shell.session.actions]]
    action = "shutdown"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "1"
    variant = "destructive"

    [[shell.session.actions]]
    action = "reboot"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "2"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "3"
    variant = "default"

    [[shell.session.actions]]
    action = "lock"
    countdown_seconds = 0.0
    enabled = false
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    countdown_seconds = 0.0
    enabled = false
    shortcut = "3"
    variant = "default"

[theme]
builtin = "Noctalia"
community_palette = "Flexoki"
custom_palette = "pytuna"
mode = "auto"
source = "custom"
wallpaper_scheme = "vibrant"

    [theme.templates]
    builtin_ids = [ "btop", "gtk3", "gtk4", "kcolorscheme", "niri", "qt" ]

[wallpaper]
directory = "/home/USERPLACEHOLDER/Pictures/Wallpapers"
fill_mode = "stretch"

    [wallpaper.automation]
    enabled = false

    [wallpaper.default]
    path = "/home/USERPLACEHOLDER/Pictures/Wallpapers/pytuna-default.jpg"

    [wallpaper.last]
    path = "/home/USERPLACEHOLDER/Pictures/Wallpapers/pytuna-default.jpg"

[widget.network]
show_label = false
