[accessibility]
ui_scale = 0.95000000670552254

[bar.default]
capsule = true
center = [ "workspaces" ]
reserve_space = false
smart_auto_hide = true
start = [ "clock" ]

[dock]
background_opacity = 0.39999999105930328
enabled = true
icon_size = 38
launcher_icon = "deer"
launcher_position = "start"
magnification_scale = 1.2500000037252903
reserve_space = false
shadow = false
show_dots = true
show_instance_count = false
smart_auto_hide = true

[location]
auto_locate = true

[shell]
font_family = "Adwaita Sans"
lang = "pt-BR"
polkit_agent = true
screen_time_enabled = true

    [shell.launcher]
    fetch_exchange_rates = false
    sort_by_usage = false

    [shell.panel]
    clipboard_placement = "attached"
    launcher_placement = "attached"
    open_near_click_clipboard = true
    open_near_click_control_center = true
    open_near_click_launcher = true
    open_near_click_session = true
    open_near_click_wallpaper = true
    polkit_placement = "attached"

    [shell.screenshot]
    directory = "~/Imagens/Capturas de Tela"

[theme]
source = "wallpaper"
wallpaper_scheme = "faithful"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4", "niri", "qt" ]

[wallpaper]
directory = "~/Imagens/Papéis de Parede"

    [wallpaper.default]
    path = "/usr/share/wallpapers/pytuna-wallpapers/pytuna-default.jpg"

[widget.battery]
color = "#669844"

[widget.bluetooth]
color = "#52A5BD"

[widget.clipboard]
color = "#F09B66"

[widget.clock]
color = "#FFFFFF"

[widget.control-center]
color = "#8360AB"

[widget.media]
art_size = 96
color = "primary"
max_length = 328
title_scroll = "on_hover"

[widget.network]
color = "#52A5BD"

[widget.notifications]
color = "hover"
hide_when_no_unread = true

[widget.session]
color = "#FF0017"

[widget.volume]
color = "primary"
show_label = false
